version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages: [emacs-nox]
  jobs:
    pre_build:
      - scripts/evil-extract-docstrings

sphinx:
  configuration: doc/source/conf.py

python:
  install:
    - requirements: doc/requirements.txt
